language: node_js

env:
  global:
    - PUBLIC_URL="mthadley.github.io/elm-quill"

node_js: "node"

script:
  - npm run build

deploy:
  github-token: $GITHUB_TOKEN
  local-dir: dist
  provider: pages
  skip-cleanup: true
  on:
    branch: master
